name: Build Android and iOS

on:
  push:
    branches: [ main ]
  # 也可以手动触发
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # 设置Java环境
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    # 设置Flutter环境
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
    
    # 获取Flutter依赖
    - name: Get dependencies
      run: flutter pub get
    
    # 构建APK
    - name: Build APK
      run: flutter build apk --release

    # 上传APK作为构建产物
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
  
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    # 设置Xcode版本
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    # 设置Flutter环境
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
    
    # 获取Flutter依赖
    - name: Get dependencies
      run: flutter pub get
    
    # 安装Pod依赖
    - name: Install Pod Dependencies
      run: |
        cd ios
        pod install
    
    # 构建iOS
    - name: Build iOS
      run: flutter build ios --release --no-codesign
    
    # 创建构建归档
    - name: Archive iOS build artifacts
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload
        zip -r app.zip Payload
        mv app.zip ../../app.ipa
    
    # 上传IPA作为构建产物
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: release-ipa
        path: build/ios/app.ipa 