name: Build Android

on:
  push:
    branches: [ main ]
  # 也可以手动触发
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      # 将APK复制到可访问的位置，避免使用upload-artifact
      - name: Copy APK to artifacts directory
        run: |
          mkdir -p /github/workspace/artifacts
          cp build/app/outputs/flutter-apk/app-release.apk /github/workspace/artifacts/
      
      # 打印APK位置信息，便于手动下载
      - name: Print artifact location
        run: |
          echo "APK built successfully! Find it in GitHub Actions build logs."
          echo "APK path: /github/workspace/artifacts/app-release.apk"
          ls -la /github/workspace/artifacts/ 