name: Build Android

on:
  push:
    branches: [ main ]
  # 也可以手动触发
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    # 添加环境变量来绕过SDK版本检查
    env:
      PUB_ALLOW_PRERELEASE_SDK: 1
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 直接下载Flutter并设置环境变量
      - name: Setup Flutter (latest stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Request the latest stable version
          channel: 'stable'
          cache: true # Enable Flutter SDK cache

      - name: Verify Flutter and Dart versions
        run: |
          echo "Flutter version:"
          flutter --version
          echo "Dart version:"
          dart --version
          echo "Pub version:"
          flutter pub --version
        shell: bash

      - name: Get Flutter dependencies (and patch video_trimmer)
        run: |
          # Try to get dependencies. This might fail due to video_trimmer but will download it.
          flutter pub get || echo "Initial pub get failed as expected, proceeding to patch."

          # Find video_trimmer in .pub-cache
          # The path will be something like: $HOME/.pub-cache/git/video_trimmer-GIT_HASH
          VIDEO_TRIMMER_DIR=$(find $HOME/.pub-cache/git -type d -name "video_trimmer-*" | head -n 1)

          if [ -z "$VIDEO_TRIMMER_DIR" ]; then
            echo "::error::video_trimmer directory not found in .pub-cache after pub get."
            # As a fallback, try to find it in a common location for direct git dependencies
            VIDEO_TRIMMER_DIR=$(find $HOME/.pub-cache/hosted/pub.dartlang.org -type d -name "video_trimmer-*" | head -n 1)
            if [ -z "$VIDEO_TRIMMER_DIR" ]; then # Still not found?
                 echo "::error::video_trimmer directory still not found after second attempt. Listing .pub-cache/git contents:"
                 ls -R $HOME/.pub-cache/git
                 exit 1
            fi
          fi
          echo "Found video_trimmer at: $VIDEO_TRIMMER_DIR"

          if [ -f "$VIDEO_TRIMMER_DIR/pubspec.yaml" ]; then
            echo "Original video_trimmer pubspec.yaml SDK constraint:"
            grep 'sdk:' "$VIDEO_TRIMMER_DIR/pubspec.yaml"
            
            # Patch the SDK constraint in video_trimmer's pubspec.yaml
            # sed -i "s/sdk: '>=3.2.3 <4.0.0'/sdk: '>=3.2.1 <4.0.0'/" "$VIDEO_TRIMMER_DIR/pubspec.yaml"
            # More robust sed: match the line and replace the version part
            sed -i -E "s/(sdk: ')[^']*/\1>=3.2.1 <4.0.0/" "$VIDEO_TRIMMER_DIR/pubspec.yaml"
            
            echo "Patched video_trimmer pubspec.yaml SDK constraint:"
            grep 'sdk:' "$VIDEO_TRIMMER_DIR/pubspec.yaml"
          else
            echo "::error::pubspec.yaml not found in $VIDEO_TRIMMER_DIR"
            exit 1
          fi

          # Now, run pub get again. It should succeed.
          flutter pub get
        shell: bash
        
      - name: Build APK
        run: flutter build apk --release
        shell: bash
        
      # 将APK复制到可访问的位置
      - name: Copy APK to artifacts directory
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
      
      # 上传构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: release-apk
          path: artifacts/app-release.apk 