name: Build Android

on:
  push:
    branches: [ main ]
  # 也可以手动触发
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    # 添加环境变量来绕过SDK版本检查
    env:
      PUB_ALLOW_PRERELEASE_SDK: 1
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      # 直接下载Flutter并设置环境变量，避免使用actions
      - name: Download and setup Flutter
        run: |
          mkdir -p $HOME/flutter
          wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz -C $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
        
      - name: Print Flutter/Dart versions
        run: |
          flutter --version
          dart --version
        
      - name: Get Flutter dependencies and clone + patch video_trimmer
        run: |
          # 先获取依赖（会失败，但会下载大部分包）
          flutter pub get || true
          
          # 查找video_trimmer目录
          VIDEO_TRIMMER_PATH=$(find $HOME/.pub-cache -name "video_trimmer" -type d | grep -v "packages/video_trimmer" | head -n 1)
          echo "Found video_trimmer at: $VIDEO_TRIMMER_PATH"
          
          if [ -n "$VIDEO_TRIMMER_PATH" ]; then
            # 修改pubspec.yaml的SDK约束
            sed -i 's/sdk: .>=3.2.3 <4.0.0./sdk: ">=3.2.1 <4.0.0"/' $VIDEO_TRIMMER_PATH/pubspec.yaml
            echo "Modified video_trimmer SDK constraint"
            cat $VIDEO_TRIMMER_PATH/pubspec.yaml | grep "sdk:"
          else
            # 如果找不到，则克隆仓库并修改
            mkdir -p $HOME/patched_packages
            cd $HOME/patched_packages
            git clone https://github.com/KyleKun/video_trimmer.git
            cd video_trimmer
            sed -i 's/sdk: .>=3.2.3 <4.0.0./sdk: ">=3.2.1 <4.0.0"/' pubspec.yaml
            echo "Patched cloned video_trimmer SDK constraint"
            cat pubspec.yaml | grep "sdk:"
            
            # 更新pubspec.yaml指向本地修补版本
            cd $GITHUB_WORKSPACE
            sed -i "s|url: https://github.com/KyleKun/video_trimmer.git|path: $HOME/patched_packages/video_trimmer|" pubspec.yaml
            sed -i "s|ref: main||" pubspec.yaml
            echo "Updated pubspec.yaml to use local patched version"
          fi
          
          # 重新获取依赖
          flutter pub get --no-pub-get-pubspec-yaml-validate
        
      - name: Build APK
        run: flutter build apk --release --no-pub
        
      # 将APK复制到可访问的位置
      - name: Copy APK to artifacts directory
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
      
      # 上传构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: artifacts/app-release.apk 